### PR TITLE
Add category for Flurry in Empty.m

### PR DESCRIPTION
**Pull request by workwithnano**

### CODE REVIEW

**Comment by shnhrrsn** [comment]
:clap: :clap: :clap: :clap: :clap: 

*PLEASE* merge this in ASAP, this cost me nearly 3 hours today.

This is also needed for FlurryAds, otherwise the ads SDK doesn't work.

**Comment by workwithnano** [comment]
@dbgrandi :point_left:  any update on this? Would like to get a client running on an official Flurry branch that supports use_frameworks

**Comment by brianmichel** [comment]
Oh hey, I was just about to make this :)

**Comment by brianmichel** [comment]
> @dbgrandi  any update on this? Would like to get a client running on an official Flurry branch that supports use_frameworks

A really cool client, I promise :)

**Comment by brianmichel** [comment]
:+1:  LGTM

**Pull request merged**
