### PR TITLE
Version updated to v6.6.0

### PR DESCRIPTION
**Pull request by tromg**

### CODE REVIEW

**Comment by jstart** [comment]
:+1:

**Comment by ajmccall** [comment]
@dbgrandi Please take a look at this PR. Looks good from my side. I validated it using 

```
pod spec lint FlurrySDK.podspec --verbose --use-libraries
```

**Comment by dbgrandi** [comment]
Merged :+1: 

I'm working on getting this moved into an official Flurry/Yahoo repository and maintained. Please bear with me during the migration.

Github **should** forward the git URL access during the migration (and keep pods working), but if you have any problems, open a ticket.

**Comment by dbgrandi** [comment]
I pushed the 6.6.0 pod.

**Comment by ajmccall** [comment]
Thank you. I've also request that Flurry take ownership of this pod as well. Thanks though.

http://blog.cocoapods.org/Claim-Your-Pods/

**Comment by dbgrandi** [comment]
@ajmccall Agreed. I work at Yahoo, and am working directly with Flurry to make that happen.

**Pull request merged**
